import * as repository from '../repositories/request.repository.js';
import { AppError } from '../utils/AppError.js';
import { allowedNext, canTransition } from '../utils/requestWorkflow.js';
import { withOverdue } from '../utils/requestOverdue.js';
export async function submit(studentId, data) { const service = await repository.findServiceForRequest(data.serviceId); if (!service) throw new AppError('Service not found', 404); if (!service.isActive || !service.departmentActive) throw new AppError('Service or department is inactive', 400); const now = new Date(); const created = await repository.createWithHistory({ studentId, service, data, dueAt: new Date(now.getTime() + service.slaHours * 60 * 60 * 1000), year: now.getFullYear() }); return repository.findByCode(created.requestCode); }
export const listMine = async (studentId, filters) => { const result = await repository.listMine(studentId, filters); return { ...result, items: result.items.map((item) => ({ ...withOverdue(item), resolutionHours: item.completedAt ? Number(((new Date(item.completedAt) - new Date(item.createdAt)) / 3600000).toFixed(1)) : null })), page: filters.page, limit: filters.limit }; };
export const summaryMine = (studentId) => repository.summaryMine(studentId);
export async function getByCode(code, user) { const request = await repository.findByCode(code); if (!request || (user.role === 'student' && request.studentId !== user.id)) throw new AppError('Request not found', 404); return { ...request, allowedNext: allowedNext(request.status), history: await repository.findHistory(request.id) }; }
export async function history(code, user) { const request = await getByCode(code, user); return request.history; }
const invalidTransition = (from, to) => new AppError(`Cannot transition from ${from} to ${to}. Allowed next states: ${allowedNext(from).join(', ') || 'none'}`, 409);
export async function changeStatus({ code, toStatus, actor, note, assignment }) { const updated = await repository.changeStatus(code, actor.id, toStatus, note, async (request) => { if (actor.role === 'student') { if (request.studentId !== actor.id) throw new AppError('Request not found', 404); if (toStatus !== 'cancelled' || request.status !== 'pending') throw invalidTransition(request.status, toStatus); } else if (actor.role === 'staff') { if (request.assignedTo !== actor.id) throw new AppError('You can only update requests assigned to you', 403); if (!['in_progress', 'completed'].includes(toStatus)) throw new AppError('You do not have permission for this action', 403); }
    if (!canTransition(request.status, toStatus)) throw invalidTransition(request.status, toStatus);
    if (assignment) return { assignedTo: assignment.id, assignedAt: new Date() };
    return {};
  }); if (!updated) throw new AppError('Request not found', 404); const result = await repository.findByCode(updated.requestCode); return { ...result, allowedNext: allowedNext(result.status) }; }
export const cancel = (code, student) => changeStatus({ code, toStatus: 'cancelled', actor: student, note: 'Request cancelled by student' });
export async function assign(code, input, actor) { const staff = await repository.findUserById(input.assignedTo); if (!staff || !staff.isActive || staff.role !== 'staff') throw new AppError('Assigned user must be an active staff member', 400); const request = await repository.findByCode(code); if (!request) throw new AppError('Request not found', 404); const updated = await repository.reassign(code, actor.id, staff.id, input.departmentId, input.note, (locked, targetDepartmentId, oldStaffName) => { if (!['pending', 'assigned', 'in_progress'].includes(locked.status)) throw new AppError('Completed or cancelled requests cannot be reassigned', 409); if (locked.assignedTo === staff.id) throw new AppError('Request is already assigned to this staff member', 409); if (staff.departmentId !== targetDepartmentId) throw new AppError('Staff member must belong to the request department', 400); return `Reassigned from ${oldStaffName || 'unassigned'} to ${staff.name}${targetDepartmentId !== locked.departmentId ? '; department changed' : ''}`; }); if (!updated) throw new AppError('Request not found', 404); const result = await repository.findByCode(updated.requestCode); return { ...result, allowedNext: allowedNext(result.status) }; }
export const updateStatus = (code, data, actor) => changeStatus({ code, toStatus: data.status, actor, note: data.note });
